database:
  host: "ep-sweet-cell-aoqerzko.c-2.ap-southeast-1.aws.neon.tech"
  port: 5432
  username: "neondb_owner"
  password: "npg_VR4XJnw7WbYT"
  database_name: "neondb"


application:
  port: 80
  host: 0.0.0.0